modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="kaokod"
description='''
Compatibility layer for First Person Model, Better Combat, Combat Roll, Curios, Artifacts, and related first-person animation integrations.
'''

[[mixins]]
config="fpm_x_compat.mixins.json"

[[dependencies.${mod_id}]]
modId="forge"
mandatory=true
versionRange="${forge_version_range}"
ordering="NONE"
side="CLIENT"

[[dependencies.${mod_id}]]
modId="minecraft"
mandatory=true
versionRange="${minecraft_version_range}"
ordering="NONE"
side="CLIENT"

[[dependencies.${mod_id}]]
modId="cloth_config"
mandatory=false
versionRange="[11.1.0,)"
ordering="AFTER"
side="CLIENT"
