# This is a neoforge.mods.toml file for First Person Model x Better Combat Compat.

modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"

[[mods]]
modId = "fpm_x_compat"
version = "${mod_version}"
displayName = "${mod_name}"
authors = "Kaokod"
description = '''
Fix First-Person Model mod issues when using mods like Better Combat, Curios, accessories, and more!
'''



[[dependencies.fpm_x_compat]]
modId = "neoforge"
type = "required"
versionRange = "[${neo_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.fpm_x_compat]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.fpm_x_compat]]
modId = "playeranimator"
type = "optional"
versionRange = "${mod_wildcard_version}"
ordering = "AFTER"
side = "CLIENT"
reason = "Provides the animation API for Mixin injection."

[[dependencies.fpm_x_compat]]
modId = "cloth_config"
type = "required"
versionRange = "${mod_wildcard_version}"
ordering = "AFTER"
side = "CLIENT"
reason = "Provides the configuration GUI."

[[dependencies.fpm_x_compat]]
modId = "firstperson"
type = "required"
versionRange = "${mod_wildcard_version}"
ordering = "AFTER"
side = "CLIENT"
reason = "Primary mod for first-person body rendering. The core of this compatibility fix."

[[dependencies.fpm_x_compat]]
modId = "bettercombat"
type = "optional"
versionRange = "${mod_wildcard_version}"
ordering = "AFTER"
side = "CLIENT"
reason = "Required for dynamic combat animation synchronization."

[[dependencies.fpm_x_compat]]
modId = "spell_engine"
type = "optional"
versionRange = "${mod_wildcard_version}"
ordering = "AFTER"
side = "CLIENT"
reason = "Optional integration for spell casting animations."

[[dependencies.fpm_x_compat]]
modId = "combatroll"
type = "optional"
versionRange = "${mod_wildcard_version}"
ordering = "AFTER"
side = "CLIENT"
reason = "Optional integration to prevent visual glitches during rolls."

[[dependencies.fpm_x_compat]]
modId = "accessories"
type = "optional"
versionRange = "${mod_wildcard_version}"
ordering = "AFTER"
side = "CLIENT"
reason = "Optional integration to hide head accessories in first-person."

[[dependencies.fpm_x_compat]]
modId = "essential"
type = "optional"
versionRange = "${mod_wildcard_version}"
ordering = "AFTER"
side = "CLIENT"
reason = "Optional integration to hide Essential cosmetics in first-person."

[[mixins]]
config = "fpm_x_compat.mixins.json"

[[mixins]]
config = "fpm_x_compat-neoforge.mixins.json"
